notice:
  label: 'Notice'
  pretext: ''
  text: 'BAIS Modernization cutover is scheduled from May 18 at 2 p.m. to May 23. The BAIS HCM, BAIS FN, and Employee Self-Service (ESS) applications will not be available during that time.'
categories:
  - title: Applications
    show_request_access_link: false
    icons: true
    apps:
      - title: Beacon
        url: https://ciboston.service-now.com/cob
        icon: https://assets.boston.gov/icons/accessboston/lighthouse_basic_icon.svg
        groups:
          - SG_AB_ESS
      - title: Employee Self-Service
        url: https://ess.boston.gov/
        icon: https://assets.boston.gov/icons/accessboston/ess.svg
        groups:
          - SG_AB_ESS
      - title: The Hub
        url: https://hub.boston.gov/saml_login
        icon: https://assets.boston.gov/icons/accessboston/hub.svg
      - title: AgilePoint
        url: https://boston.nxone.com
        icon: https://assets.boston.gov/icons/accessboston/agilepoint.svg
        groups:
          - SG_AB_AGILEPOINT
      - title: Security Awareness
        url: https://boston.wombatsecurity.com
        icon: https://assets.boston.gov/icons/accessboston/proofpoint-web-security.svg
        groups:
          - SG_AB_PROOFPOINT
      - title: Current Job Openings
        url: https://sso.boston.gov/idp/startSSO.ping?PartnerSpId=icims.com&TargetResource=https%3A//employeeconnect-boston.icims.com/r.jsp
        icon: https://assets.boston.gov/icons/accessboston/job-openings.svg
        groups:
          - SG_AB_ICIMS
      - title: Current Job Openings
        icon: https://assets.boston.gov/icons/accessboston/job-openings.svg
        url: https://careercenter-boston.icims.com/jobs/
        groups:
          - SG_AB_ALLSPONSORED
      - title: Career Center
        url: https://sso.boston.gov/idp/startSSO.ping?PartnerSpId=icims.com
        icon: https://assets.boston.gov/icons/accessboston/career-center.svg
        groups:
          - SG_AB_CAREERCTR
      - title: BPS Job Listings
        url: https://bostonpublicschools.tedk12.com/hire/index.aspx
        icon: https://assets.boston.gov/icons/accessboston/talented.svg
      - title: Employee Training
        url: https://sso.boston.gov/idp/startSSO.ping?PartnerSpId=http%3A%2F%2Fwww.mylearningplan.com%2Fmvc%2Fsaml%2Fmetadata%2F13583
        icon: https://assets.boston.gov/icons/accessboston/employee-training.svg
        groups:
          - SG_AB_MLP
      - title: Boston Maps
        url: https://sso.boston.gov/idp/startSSO.ping?PartnerSpId=boston.maps.arcgis.com
        icon: https://assets.boston.gov/icons/accessboston/boston-maps.svg
      - title: Tableau
        url: https://dashboard.cityofboston.gov/
        icon: https://assets.boston.gov/images/access_boston/Tableau.png
        groups:
          - SG_AB_TABLEAU
      - title: BAIS FN
        url: https://fn.boston.gov/psp/psfnprd/EMPLOYEE/ERP/h/?tab=DEFAULT
        icon: https://assets.boston.gov/icons/accessboston/bais-fn.svg
        groups:
          - SG_AB_PSFN
      - title: BAIS HCM
        url: https://hcm.boston.gov/psp/pshrprd/EMPLOYEE/HRMS/h/?tab=DEFAULT
        icon: https://assets.boston.gov/icons/accessboston/bais-hcm.svg
        groups:
          - SG_AB_PSHCM
      - title: Hyperion
        url: https://planning-a423759.pbcs.us2.oraclecloud.com/workspace
        icon: https://assets.boston.gov/icons/accessboston/hyperion.svg
        groups:
          - SG_AB_HYPERION
      - title: Civis
        url: https://sso.boston.gov/idp/startSSO.ping?PartnerSpId=https%3A%2F%2Fplatform.civisanalytics.com%2Fusers%2Fsaml%2Fmetadata
        icon: https://assets.boston.gov/icons/accessboston/civis.svg
        groups:
          - SG_AB_CIVIS
      - title: IIQ
        url: https://identity.boston.gov/identityiq/
        icon: https://assets.boston.gov/icons/accessboston/identityiq.svg
        groups:
          - SG_AB_IAM_TEAM
      - title: E-Builder
        url: https://sso.boston.gov/idp/startSSO.ping?PartnerSpId=sso.e-builder.net
        icon: https://assets.boston.gov/icons/accessboston/e-builder.svg
        groups:
          - SG_AB_EBUILDER
      - title: Riskmaster
        url: https://sso.boston.gov/idp/startSSO.ping?PartnerSpId=https%3A%2F%2Frmaprdcityofboston.dxc-ins.com
        icon: https://assets.boston.gov/icons/accessboston/Riskmaster2.svg
        groups:
          - SG_AB_RISKMASTER
      - title: Asset Essentials
        url: https://assetessentials.dudesolutions.com/CityOfBoston/
        icon: https://assets.boston.gov/icons/accessboston/asset_essentials.svg
        groups:
          - SG_AB_ASSETESSENTIALS
      - title: Edit Boston.gov
        url: https://content.boston.gov/saml_login?ReturnTo=https://content.boston.gov/admin/workbench
        icon: https://assets.boston.gov/icons/experiential_icons/hero_image.svg
        groups:
          - SG_AB_BOSTONDOTGOV
          - SG_AB_DRUPAL_ADMIN
          - SG_AB_DRUPAL_CONTENTEDITOR
          - SG_AB_DRUPAL_CONTENTAUTHOR
          - SG_AB_DRUPAL_METROAUTHOR
          - SG_AB_DRUPAL
      - title: Phire
        url: https://phireprd.bais.boston.gov/psp/phire/EMPLOYEE/PT_LOCAL/h/?tab=DEFAULT
        icon: https://assets.boston.gov/icons/accessboston/Phire.svg
        groups:
          - SG_AB_PHIRE
      - title: Xybion
        url: https://sso.boston.gov/idp/startSSO.ping?PartnerSpId=https%3A%2F%2Fma.xybion.com%2Fsso%2Fmetadata.xml
        icon: https://assets.boston.gov/icons/accessboston/Xybion.svg
        groups:
          - SG_AB_XYBION
      - title: Gov QA
        url: https://sso.boston.gov/idp/startSSO.ping?PartnerSpId=bostonma.govqa.us
        icon: https://assets.boston.gov/icons/accessboston/gov_qa.svg
        groups:
          - SG_AB_GOVQA
      - title: ScerIS
        url: https://sso.boston.gov/idp/startSSO.ping?PartnerSpId=urn%3Asso%3AScerIS
        icon: https://assets.boston.gov/icons/accessboston/sceris.svg
        groups:
          - SG_AB_SCERIS
      - title: ServiceNow - Lightkeeper
        url: https://sso.boston.gov/idp/startSSO.ping?PartnerSpId=https%3A%2F%2Fciboston.service-now.com
        icon: https://assets.boston.gov/icons/accessboston/lantern.svg
        groups:
          - SG_AB_SNOWADMIN
      - title: COVID Compliance
        url: https://ciboston.service-now.com/covid
        icon: https://assets.boston.gov/icons/accessboston/health_protection.svg
      - title: V3
        url: https://sso.boston.gov/idp/startSSO.ping?PartnerSpId=urn%3Aauth0%3Av3locity%3Abrs-prod-provider
        icon: https://assets.boston.gov/icons/accessboston/v3.svg
        groups:
          - SG_AB_V3
          - SG_AB_GRPMGMT_V3
      - title: CyberArk
        url: https://pam.boston.gov/
        icon: https://assets.boston.gov/icons/accessboston/cyberark.svg
        groups:
          - SG_AB_CYBERARK
      - title: Tanium
        url: https://boston.cloud.tanium.com
        icon: https://assets.boston.gov/icons/experiential_icons/secure.svg
        groups: 
          - SG_AB_TANIUM
      - title: FHE Salesforce
        url: https://cob.my.salesforce.com
        icon: https://assets.boston.gov/icons/experiential_icons/house_2.svg
        groups:
          - SG_AB_FHESALESFORCE
      - title: Confirm ID
        url: /confirmid
        target: _blank
        icon: https://assets.boston.gov/icons/accessboston/identity_verification.svg
        groups:
          - SG_AB_CONFIRMID

  - title: Forms / Links
    apps:
      - title: Create Sponsored Account
        url: https://identity.boston.gov/identityiq/createSponsor.jsf
        groups:
          - SG_AB_SPONSOR
      - title: FleetHub
        url: http://boston.getlocalmotion.com/
        groups:
          - SG_AB_ALLSPONSPONSERED
        agencies:
          - CH
      - title: International Travel
        url: https://goo.gl/forms/Xobh9aZeGXSnKH2m2
        groups:
          - SG_AB_ALLSPONSPONSERED
        agencies:
          - BPD
          - BFD
          - CH
      - title: Building Maintenance
        url: https://assetessentials.dudesolutions.com/CityOfBoston/MyRequest/Add
        agencies:
          - CH
        groups:	
          - SG_AB_BLDGMAINTREQ
          - SG_AB_ALLSPONSPONSERED
      - title: Request FN Access
        url: https://identity.boston.gov/identityiq/requestPsfn.jsf
        groups:
          - SG_AB_FN_LIASONS_USERS

  - title: Account Tools
    apps:
      - title: Change My Password
        url: /change-password
      - title: Manage My Device(s)
        url: https://desktop.pingone.com/boston/Selection?cmd=devices
        mfa_device_required: true

  - title: Support Tools
    apps:
      - title: Identity Verification
        url: https://identity.boston.gov/identityiq/identityVerification.jsf
        groups:
          - SG_AB_SERVICEDESK_USERS
      - title: View User Information
        url: https://identity.boston.gov/identityiq/viewUserIdentityonly.jsf
        groups:
          - SG_AB_SERVICEDESK_USERS
          - SG_AB_ALLSPONSPONSERED
      - title: Edit Group
        url: "#"
        groups:
          - SG_AB_HCMSECURITY
      - title: Group Management
        url: /group-management
        target: _blank

  - title: Manager Tools
    apps:
      - title: Set an Access Boston Delegate
        url: https://identity.boston.gov/identityiq/dashboard/identityPreferences.jsf#/identityPreferences
        groups:
          - SG_AB_MANAGER
          - SG_AB_TRAINING_TEAM
          - SG_AB_FN_LIASONS_USERS
      - title: My Access Boston Approvals
        url: https://identity.boston.gov/identityiq/manage/workItems/workItems.jsf?workItemType=Approval
        groups:
          - SG_AB_MANAGER
          - SG_AB_TRAINING_TEAM
          - SG_AB_FN_LIASONS_USERS
      - title: Manage Sponsored Account
        url: https://identity.boston.gov/identityiq/extendSponsor.jsf
        groups:
          - SG_AB_SPONSOR
