os: linux
dist: xenial
language: node_js
node_js:
- '11.14.0'
cache:
  directories:
    - node_modules
branches:
  only:
    - master
install:
  - npm install
jobs:
  include:
    - name: Javascript Tests
      script: npm run test
    - stage: deploy
      deploy:
        - provider: s3
          on: 
            branch: master
          cleanup: true
          access_key_id: "$AWS_ACCESS_KEY_ID"
          secret_access_key: "$AWS_SECRET_ACCESS_KEY"
          bucket: cob-digital-apps-staging-static
          region: "$AWS_DEFAULT_REGION"
          local_dir: src/configs
          upload_dir: access-boston-config
        - provider: s3
          on: 
            branch: master
          cleanup: true
          access_key_id: "$AWS_ACCESS_KEY_ID"
          secret_access_key: "$AWS_SECRET_ACCESS_KEY"
          bucket: cob-digital-apps-access-boston-config-dev
          region: "$AWS_DEFAULT_REGION"
          local_dir: src/configs/dev
          upload_dir: config

notifications:
  slack:
    if: branch = master
    rooms: [ "cityofboston-doit:azFYl0Jini0k7aZOT3nexuNO" ]
    template:
      - "Repo %{repository_slug} %{result} build (<%{build_url}|#%{build_number}>) for commit (<%{compare_url}|%{commit}>) on branch %{branch}."
      - "Execution time: %{duration}"
      - "Message: %{message}"
  email:
    recipients:
      - digital-dev@boston.gov
      - phillip.kelly@boston.gov
      - phillipbentonkelly@gmail.com
      - phill2k12@gmail.com
