language: node_js
node_js:
- '11.14.0'
cache:
  directories:
    - node_modules
branches:
  only:
    - master
install:
  - npm install
jobs:
  include:
    - name: Javascript Tests
      script: npm run test
    - stage: deploy
      deploy:
        - provider: s3
          skip_cleanup: true
          access_key_id: "$AWS_ACCESS_KEY_ID"
          secret_access_key: "$AWS_SECRET_ACCESS_KEY"
          bucket: cob-digital-apps-staging-static
          region: "$AWS_DEFAULT_REGION"
          local_dir: src/configs
          upload-dir: access-boston-config

notifications:
  slack: cityofboston-doit:azFYl0Jini0k7aZOT3nexuNO