language: node_js
node_js:
- '11.14.0'
cache:
  directories:
    - node_modules
branches:
  only:
    - master
install:
  - npm install
jobs:
  include:
    - name: Javascript Tests
      script: npm run test
